apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: budgetah-backend-data
  labels:
    app: budgetah-backend
    group: budgetah
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi